name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2-beta
      with:
        go-version: 1.14

    - name: Run linter
      run: go vet ./...

    - name: Run tests
      run: go test ./...  
      env:
        REDIS_HOST: 0.0.0.0
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
